// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

typedef struct _ui_anim_user_data_t {
    lv_obj_t * target;
    lv_image_dsc_t ** imgset;
    int32_t imgset_size;
    int32_t val;
} ui_anim_user_data_t;


void _ui_anim_callback_set_opacity(lv_anim_t * a, int32_t v);
int32_t _ui_anim_callback_get_opacity(lv_anim_t * a);
void _ui_anim_callback_free_user_data(lv_anim_t * a);

///////////////////// SCREENS ////////////////////

//#include "screens/ui_mainscreen.h"

///////////////////// VARIABLES ////////////////////

//extern lv_anim_t * heatanimation_Animation(lv_obj_t * TargetObject, int delay);
//extern lv_anim_t * heatanim_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

//extern lv_obj_t * ui____initial_actions0;


// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_frame_00_png);    // assets/frame_00.png
LV_IMG_DECLARE(ui_img_wifi_error_png);    // assets/wifi-icon-3788-ezgif.com-instagif.png
LV_IMG_DECLARE(ui_img_wifi_png);    // assets/wifi-icon-3788-ezgif.com-instagif.png


// FONTS
//LV_FONT_DECLARE(ui_font_belg40all);
//LV_FONT_DECLARE(ui_font_belgrado16);
//LV_FONT_DECLARE(ui_font_belgrado40);
//LV_FONT_DECLARE(ui_font_gathegap16);
//LV_FONT_DECLARE(ui_font_gatherbrk16);
//LV_FONT_DECLARE(ui_font_gatherbrk18);
//LV_FONT_DECLARE(ui_font_gatherbrk40);
//LV_FONT_DECLARE(ui_font_hemihead16);
//LV_FONT_DECLARE(ui_font_hemihead20);
//LV_FONT_DECLARE(ui_font_hemihead40);
LV_FONT_DECLARE(ui_font_hemihead60);
//LV_FONT_DECLARE(ui_font_luckguy40);
//LV_FONT_DECLARE(ui_font_segblack40);
LV_FONT_DECLARE(ui_font_segblack20);
LV_FONT_DECLARE(ui_font_segblack16);

// UI INIT
//void ui_init(void);
//void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
